CREATE DATABASE CUSTOMER;
USE CUSTOMER;
Show tables;

CREATE TABLE IF NOT EXISTS CUSTOMER_X(
ID INT NOT NULL,
NAME VARCHAR(20) NOT NULL,
AGE INT NOT NULL,
ADDRESS VARCHAR(25),
SALARY DECIMAL(18,2),
PRIMARY KEY(ID)
);

INSERT INTO CUSTOMER_X VALUES(1,"RUPALI",25,"VADODARA",50000);
INSERT INTO CUSTOMER_X VALUES(2,"ABC",24,"AHMEDABAD",20000);
INSERT INTO CUSTOMER_X VALUES(3,"DEF",35,"BHARUCH",25000);
INSERT INTO CUSTOMER_X VALUES(4,"PQR",30,"RAJKOT",18000);
INSERT INTO CUSTOMER_X VALUES(5,"XYZ",40,"SURAT",46000);
SELECT * FROM CUSTOMER_X;

CREATE TABLE IF NOT EXISTS ORDERS(
ORDER_ID INT NOT NULL,
ORDER_NUMBER INT NOT NULL,
ID INT,
PRIMARY KEY(ORDER_ID),
CONSTRAINT FK_CUSTOMERORDER FOREIGN KEY(ID)
REFERENCES CUSTOMER_X(ID)
);

INSERT INTO ORDERS VALUES(1001,101,1);
INSERT INTO ORDERS VALUES(1002,102,2);
INSERT INTO ORDERS VALUES(1003,103,3);
INSERT INTO ORDERS VALUES(1004,104,4);
INSERT INTO ORDERS VALUES(1005,105,5);
SELECT * FROM ORDERS;
desc orders;

INSERT INTO ORDERS VALUES(1006,106,6);
INSERT INTO ORDERS VALUES(1007,107,7);
INSERT INTO ORDERS VALUES(1008,108,8);
INSERT INTO ORDERS VALUES(1009,109,9);
INSERT INTO ORDERS VALUES(1010,110,10);
SELECT * FROM ORDERS;

ALTER TABLE ORDERS ADD FOREIGN KEY(ID) REFERENCES CUSTOMER_X(ID);
SELECT * FROM ORDERS;

ALTER TABLE ORDERS DROP FOREIGN KEY FK_CUSTOMER_ORDER

CREATE TABLE IF NOT EXISTS ORDERS(
ORDER_ID INT NOT NULL,
ORDER_NUMBER INT NOT NULL,
ID INT,
PRIMARY KEY(ORDER_ID)
);

INSERT INTO ORDERS VALUES(1001,101,1);
INSERT INTO ORDERS VALUES(1002,102,2);
INSERT INTO ORDERS VALUES(1003,103,3);
INSERT INTO ORDERS VALUES(1004,104,4);
INSERT INTO ORDERS VALUES(1005,105,5);
INSERT INTO ORDERS VALUES(1006,106,6);
INSERT INTO ORDERS VALUES(1007,107,7);
INSERT INTO ORDERS VALUES(1008,108,8);
INSERT INTO ORDERS VALUES(1009,109,9);
INSERT INTO ORDERS VALUES(1010,110,10);
SELECT * FROM ORDERS;

CREATE TABLE CUSTOMER_INFO(ID INT(10), FIRST_NAME VARCHAR(10), LAST_NAME VARCHAR(10));
SHOW TABLES;
INSERT INTO CUSTOMER_INFO(ID,FIRST_NAME,LAST_NAME) VALUES(1,"RUPALI","CHHATROLA");
INSERT INTO CUSTOMER_INFO(ID,FIRST_NAME,LAST_NAME) VALUES(2,"ABC","XYZ");
INSERT INTO CUSTOMER_INFO(ID,FIRST_NAME,LAST_NAME) VALUES(3,"XYZ1","ABC1");
SELECT * FROM CUSTOMER_INFO;
UPDATE CUSTOMER_INFO SET FIRST_NAME="MANYA" WHERE ID=1;