CREATE DATABASE IF NOT EXISTS RETAIL;
USE RETAIL;
CREATE TABLE IF NOT EXISTS ONLINE_RETAIL(
INVOICE_NO INT NOT NULL,
STOCK_CODE VARCHAR(15) NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL,
QUANTITY INT NOT NULL,
INVOICE_DATE DATE NOT NULL,
UNIT_PRICE DECIMAL(4,2) NOT NULL,
CUSTOMER_ID INT NOT NULL,
COUNTRY VARCHAR(30)
);

set session sql_mode=' ';

LOAD DATA INFILE
'D:\Online_Retail.csv' 
INTO TABLE ONLINE_RETAIL
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS

SELECT * FROM ONLINE_RETAIL;