USE WORLD;
SHOW TABLES;
SELECT * FROM COUNTRY;
SELECT COUNT(REGION),CONTINENT FROM COUNTRY GROUP BY(CONTINENT) HAVING COUNT(REGION) >6;
SELECT * FROM COUNTRY GROUP BY(CONTINENT) HAVING COUNT(REGION) >6;
